#!/usr/bin/env bash
#DESC:Tiny template app used to verify placeholder-backed equivalence keys
#ARCH:noarch
#REDISTRIBUTE:yes
#TARGET:template-message/{flavor}

#PH:flavor:red,blue

mkdir -p "$CNT_PREFIX/bin"
printf '%s\n' '{flavor}' > "$CNT_PREFIX/flavor.txt"

cat > "$CNT_PREFIX/bin/cnt-template-message" <<'EOT'
#!/bin/sh
cat "$(dirname "$0")/../flavor.txt"
EOT
chmod 0755 "$CNT_PREFIX/bin/cnt-template-message"
